import React from 'react'

import { GRPCSelfGeneratedAPIReference } from 'grpc-docs'

const Example = () => {
  return <GRPCSelfGeneratedAPIReference file='url-to-json-description-of-api'/>

  return <GRPCSelfGeneratedAPIReference definition='A json string definition that got generated by protoc'/>

  return <GRPCSelfGeneratedAPIReference file='example-descriptors/description.json'/>
}

export default App